# Import .env file natively
spring.config.import=optional:file:.env

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JWT Configuration
jwt.secret=${JWT_SECRET}

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Cloudinary
cloudinary.url=${CLOUDINARY_URL}

# Mail Configuration (For OTP)
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Server Port
server.port=8081

# File Upload Limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Server Scaling (10,000 Active Users)
server.tomcat.threads.max=2000
server.tomcat.threads.min-spare=200
server.tomcat.accept-count=10000
server.tomcat.max-connections=20000

# Database Connection Pooling (HikariCP)
spring.datasource.hikari.maximum-pool-size=500
spring.datasource.hikari.minimum-idle=100
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000
# Security
app.cors.allowed-origins=http://localhost:5173,http://172.30.18.6:5173
